# Generated by Django 2.1.15 on 2020-10-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weather',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
