# Generated by Django 2.1.15 on 2020-09-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.Check_list')),
            ],
        ),
    ]
