# Generated by Django 2.1.15 on 2020-10-02 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
        ('checks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_date', to='utilities.Date'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplies',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_place', to='utilities.Place'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='stuffs',
            field=models.ManyToManyField(blank=True, related_name='supply_stuff', to='checks.Stuff'),
        ),
    ]
