# Generated by Django 2.1.15 on 2020-09-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_auto_20200922_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkimage',
            name='image',
        ),
    ]
