# Generated by Django 2.1.15 on 2020-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_remove_checkimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictureset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlpicture', models.TextField()),
            ],
        ),
    ]
